import React, { useEffect, useState } from "react";
import {
  View,
  StyleSheet,
  ScrollView,
  Pressable,
  Share,
  Platform,
  ToastAndroid,
  Alert,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useHeaderHeight } from "@react-navigation/elements";
import { useRoute, useNavigation } from "@react-navigation/native";
import { MaterialIcons, Ionicons } from "@expo/vector-icons";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as Clipboard from "expo-clipboard";
import * as Haptics from "expo-haptics";
import type { RouteProp } from "@react-navigation/native";

import { ThemedView } from "@/components/ThemedView";
import { ThemedText } from "@/components/ThemedText";
import { useTheme } from "@/hooks/useTheme";
import { Spacing, BorderRadius } from "@/constants/theme";
import { getNote, SavedNote } from "@/lib/storage";
import type { RootStackParamList } from "@/navigation/RootStackNavigator";

const stripMarkdown = (text: string): string => {
  return text
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/__(.*?)__/g, "$1")
    .replace(/_(.*?)_/g, "$1")
    .replace(/`(.*?)`/g, "$1");
};

const showToast = (message: string) => {
  if (Platform.OS === "android") {
    ToastAndroid.show(message, ToastAndroid.SHORT);
  } else {
    Alert.alert("Success", message);
  }
};

type NoteDetailRouteProp = RouteProp<RootStackParamList, "NoteDetail">;

export default function NoteDetailScreen() {
  const insets = useSafeAreaInsets();
  const headerHeight = useHeaderHeight();
  const { theme } = useTheme();
  const route = useRoute<NoteDetailRouteProp>();
  const navigation = useNavigation();

  const [note, setNote] = useState<SavedNote | null>(null);

  useEffect(() => {
    loadNote();
  }, [route.params.noteId]);

  const loadNote = async () => {
    const fetchedNote = await getNote(route.params.noteId);
    setNote(fetchedNote);
    if (fetchedNote) {
      navigation.setOptions({ headerTitle: fetchedNote.title });
    }
  };

  const copyToClipboard = async () => {
    if (!note) return;
    await Clipboard.setStringAsync(note.content);
    if (Platform.OS !== "web") {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    }
    showToast("Copied to clipboard");
  };

  const shareNote = async () => {
    if (!note) return;
    try {
      await Share.share({
        message: `${note.title}\n\n${note.content}`,
        title: note.title,
      });
    } catch (error) {
      console.error("Error sharing:", error);
    }
  };

  const exportPDF = async () => {
    if (!note) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${note.title}</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
              padding: 40px;
              line-height: 1.6;
              color: #111827;
            }
            h1 {
              color: #2563EB;
              border-bottom: 2px solid #2563EB;
              padding-bottom: 10px;
              margin-bottom: 20px;
            }
            h2 {
              color: #1F2937;
              margin-top: 24px;
              margin-bottom: 12px;
            }
            ul {
              margin: 0;
              padding-left: 20px;
            }
            li {
              margin-bottom: 8px;
            }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #E5E7EB;
              color: #6B7280;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          <h1>${note.title}</h1>
          ${note.content.split("\n").map((line) => {
            if (line.startsWith("## ")) {
              return `<h2>${line.substring(3)}</h2>`;
            } else if (line.startsWith("- ")) {
              return `<li>${line.substring(2)}</li>`;
            } else if (line.trim() === "") {
              return "<br/>";
            }
            return `<p>${line}</p>`;
          }).join("")}
          <div class="footer">
            Generated by Exam Notes | ${new Date(note.createdAt).toLocaleDateString()}
          </div>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({
        html: htmlContent,
        base64: false,
      });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: "application/pdf",
          dialogTitle: `Share ${note.title}`,
        });
        showToast("PDF ready to save");
      }

      if (Platform.OS !== "web") {
        Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      }
    } catch (error) {
      console.error("Error exporting PDF:", error);
      showToast("Failed to create PDF");
    }
  };

  if (!note) {
    return (
      <ThemedView style={styles.container}>
        <View style={styles.loadingContainer}>
          <ThemedText>Loading...</ThemedText>
        </View>
      </ThemedView>
    );
  }

  return (
    <ThemedView style={styles.container}>
      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={[
          styles.content,
          {
            paddingTop: headerHeight + Spacing.lg,
            paddingBottom: insets.bottom + Spacing.xl,
          },
        ]}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.actions}>
          <Pressable
            style={[styles.actionButton, { backgroundColor: theme.backgroundSecondary }]}
            onPress={copyToClipboard}
          >
            <MaterialIcons name="content-copy" size={18} color={theme.text} />
            <ThemedText type="small">Copy</ThemedText>
          </Pressable>

          <Pressable
            style={[styles.actionButton, { backgroundColor: theme.backgroundSecondary }]}
            onPress={shareNote}
          >
            <MaterialIcons name="share" size={18} color={theme.text} />
            <ThemedText type="small">Share</ThemedText>
          </Pressable>

          <Pressable
            style={[styles.actionButton, { backgroundColor: theme.link }]}
            onPress={exportPDF}
          >
            <MaterialIcons name="picture-as-pdf" size={18} color="#FFFFFF" />
            <ThemedText type="small" style={{ color: "#FFFFFF" }}>
              PDF
            </ThemedText>
          </Pressable>
        </View>

        <View style={styles.noteContent}>
          {note.content.split("\n").map((line, index) => {
            if (line.startsWith("## ")) {
              return (
                <ThemedText
                  key={index}
                  type="h3"
                  style={[styles.heading, { color: theme.link }]}
                >
                  {stripMarkdown(line.substring(3))}
                </ThemedText>
              );
            } else if (line.startsWith("# ")) {
              return (
                <ThemedText
                  key={index}
                  type="h2"
                  style={[styles.mainHeading, { color: theme.link }]}
                >
                  {stripMarkdown(line.substring(2))}
                </ThemedText>
              );
            } else if (line.startsWith("- ")) {
              return (
                <View key={index} style={styles.bulletItem}>
                  <View style={[styles.bulletDot, { backgroundColor: theme.link }]} />
                  <ThemedText type="body" style={styles.bulletText}>
                    {stripMarkdown(line.substring(2))}
                  </ThemedText>
                </View>
              );
            } else if (line.startsWith("* ")) {
              return (
                <View key={index} style={styles.bulletItem}>
                  <View style={[styles.bulletDot, { backgroundColor: theme.link }]} />
                  <ThemedText type="body" style={styles.bulletText}>
                    {stripMarkdown(line.substring(2))}
                  </ThemedText>
                </View>
              );
            } else if (line.trim() !== "") {
              return (
                <ThemedText key={index} type="body" style={styles.paragraph}>
                  {stripMarkdown(line)}
                </ThemedText>
              );
            }
            return <View key={index} style={styles.spacer} />;
          })}
        </View>

        <View style={styles.metadata}>
          <View style={styles.metadataRow}>
            <MaterialIcons
              name={note.sourceType === "ocr" ? "photo-camera" : "edit"}
              size={14}
              color={theme.textSecondary}
            />
            <ThemedText type="small" style={{ color: theme.textSecondary }}>
              {note.sourceType === "ocr" ? "Created from images" : "Created from text"}
            </ThemedText>
          </View>
          <ThemedText type="small" style={{ color: theme.textSecondary }}>
            {new Date(note.createdAt).toLocaleDateString("en-US", {
              month: "long",
              day: "numeric",
              year: "numeric",
              hour: "2-digit",
              minute: "2-digit",
            })}
          </ThemedText>
        </View>
      </ScrollView>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: Spacing.lg,
    gap: Spacing.xl,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  actions: {
    flexDirection: "row",
    gap: Spacing.sm,
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.sm,
  },
  noteContent: {
    gap: Spacing.md,
  },
  mainHeading: {
    marginTop: Spacing.xl,
    marginBottom: Spacing.sm,
    fontSize: 22,
    fontWeight: "700",
  },
  heading: {
    marginTop: Spacing.lg,
    marginBottom: Spacing.sm,
    fontSize: 18,
    fontWeight: "600",
  },
  paragraph: {
    lineHeight: 26,
    fontSize: 16,
  },
  bulletItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingLeft: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  bulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginTop: 10,
    marginRight: 12,
  },
  bulletText: {
    flex: 1,
    lineHeight: 26,
    fontSize: 16,
  },
  spacer: {
    height: Spacing.md,
  },
  metadata: {
    borderTopWidth: 1,
    borderTopColor: "rgba(128,128,128,0.2)",
    paddingTop: Spacing.lg,
    gap: Spacing.xs,
  },
  metadataRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
});
